spring:
  application:
    name: uaa
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/uaa_srv?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 180000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      minimum-idle: 5 # 最小空闲连接数量
      idle-timeout: 180000 # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 # 连接池最大连接数，默认是10
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: uaa-hikaricp
      connection-test-query: SELECT 1
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  thymeleaf:
    cache: false
    prefix: classpath:/views/
    mode: HTML
security:
  oauth2:
    client:
      authentication-scheme: header
      client-authentication-scheme: header
      client-id: pc
      client-secret: pc

jwt:
  keystorepass: admin123

server:
  port: 7003

debug: true



